### ISSUE TITLE
Fichier "Inversion.COMM" $7

### ISSUE THREAD

**Issue by GuillaumeSchuler** [agnes-riviere/ginette#5]
The $7 parameter of the Inversion.COMM is the "thickness of the studied hyporheic zone (= distance between the 2 furthest working PT100, in meters)". If the deepest (= 4th) PT100 is broken, should people still write the distance between the upper BD (= stream temperature sensor) and the 4th PT100, or only with the 3th PT100 ? The fact that it could affect the simulation of the pressure data is to be taken into account.

**Comment by GuillaumeSchuler** [comment]
For the Avenelles data, the following points are particularly concerned : 
- P38 : 4th (=deepest) PT100 not working
- P39 : Stream T sensor + 4th PT100 not working
- P41 : 4th PT100 not working

**Comment by agnes-riviere** [comment]
This issue is resolved for the P38, P41 and P43
